### ISSUE TITLE
Bad alignment of last line of data

### ISSUE THREAD

**Issue by dfdiego** [Droppers/HexEditorControl#3]
Hello,

Your project looks very promising! I've made some tests because I needed an hex control for Avalonia. When the last line of data contains less bytes of the maximum number of bytes, the decoded text is showed not in its "column" but after the hex bytes instead. You can see in the image below:

![image](https://user-images.githubusercontent.com/11890541/161269548-4dfd7e73-dcb3-4a85-abb0-29ebfbc4ccf1.png)

Don't know if you fixed in the latest days, I tried with sources of 20/02/2022.

I've implemented the "memory" buffer in order to make some tests, if you need, here is the source code of MemoryBuffer.cs under "HexEditorControl-main\src\Shared\HexControl.Core\Buffers\":

```
using System;
using System.Collections.Generic;
using System.IO.MemoryMappedFiles;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using HexControl.Core.Buffers.Chunks;

namespace HexControl.Core.Buffers
{
    public class MemoryBuffer : BaseBuffer, IDisposable
    {
        private byte[] m_RawData { get; set; }

        public MemoryBuffer( byte[] rawData )
        {
            m_RawData = rawData;

            var chunk = new MemoryChunk( this, rawData );

            Init( chunk );
        }

        public void Dispose()
        {
            m_RawData = null;
        }

        protected override long FindInVirtual( IFindStrategy strategy, long offset, long length, FindOptions options,
            CancellationToken cancellationToken ) =>
            strategy.SearchInBuffer( m_RawData, offset, length, options.Backward );
    }
}

```

In order to use it, in the "HexEditorControl-main\src\Shared\HexControl.Core\Document.cs":

```
    public static Document FromBuffer(byte[] bytes, DocumentConfiguration? configuration = null) =>
        new(new MemoryBuffer(bytes), configuration);
```

Thank you for the good work!

**Comment by Droppers** [comment]
Hey,

The rendering of the final row is indeed something that needs to be fixed, haven't had time for it yet. 

And thank you for the memory buffer :)!

I'm hoping to finish saving files this weekend, and  to allow for converting a document with a memory buffer to a file buffer. 

After that I'll work on the rendering.

**Comment by Droppers** [comment]
I have now implemented a MemoryBuffer

**Comment by Droppers** [comment]
Saving files and memory buffers has now been implemented. If you sometime want to use this control, let me know what features you need that are missing :)!

**Comment by dfdiego** [comment]
Nice! The last line is now aligned. 

As other features, I'll think about while I use it. Only one question: is it possible to switch from the dark mode colors to a light mode ?

**Comment by Droppers** [comment]
Hi! Don't know if you still need it, but preview packages are now available on the following NuGet feed:
```
https://www.myget.org/F/joery/api/v3/index.json
```
