### ISSUE TITLE
DevExpress Dependencies Causing Nuget Installation Failure (WinForms)

### ISSUE THREAD

**Issue by vector-man** [Droppers/HexEditorControl#8]
I get the following errors, when installing version v1.5.0.4 for WinForms on Nuget:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package DevExpress.Win.Design. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package DevExpress.Win.Dialogs. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
```

**Comment by Droppers** [comment]
That's another package (not mine), I wouldn't dare to touch DevExpress 😄. Currently only 'alpha' packages are available on MyGet.

You have to add the following NuGet feed (include prerelease versions):
```
https://www.myget.org/F/joery/api/v3/index.json
```

For WinForms the package is named `HexControl.WinForms`.

Over the past few days, I have made a lot of changes which should make it a lot more stable.
